In [3]:
import numpy as np

## Method to create array

1. np.arange()

2. np.linespace()

3. np.ones()

4. np.zeros()

5. np.full()

6. np.eye()

In [ ]:
# np.arange(): serese of eqally space numbers

np.arange(start=0,stop=10,step=2) 
 # start(inclusuve and default -->0)
 # stop(exclusive)
 # step(default-->1)
 # return type --->ndarray(int)

array([0, 2, 4, 6, 8])

In [ ]:
# np.linspace()  : return of arary of qyally spaced number b/w start (inclusive) and stop (inclusive)
# num=50(default it generate the number)

np.linspace(start=1,stop=20,num=5)
# np.linspace(start=1,stop=20,num=10)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [14]:
np.linspace(start=1,stop=20,num=5,retstep=True)

(array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ]), np.float64(4.75))

In [15]:
np.linspace(start=1,stop=20,num=5,endpoint=False,retstep=True)

(array([ 1. ,  4.8,  8.6, 12.4, 16.2]), np.float64(3.8))

In [21]:
# np.ones() : return array of ones in float

np.ones(shape=(3,))

array([1., 1., 1.])

In [18]:
np.ones(shape=(3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.ones(shape=(3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
# np.zeros()  : return array of zeros in float
np.zeros(shape=(3,))

array([0., 0., 0.])

In [28]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# np.zeros(shape=(3,),dtype=float)

array([0., 0., 0.])

In [ ]:
# np.full() : return the array of values 
# same value will be filled for the given shape

np.full(shape=(3,),fill_value=100)
np.full(shape=(3,2),fill_value=100)

array([[100, 100],
       [100, 100],
       [100, 100]])

In [40]:
# np.eye(): return the identity materix

np.eye(N=3)  # n-->row ,m-->col(default m=n)
# sqared materix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.eye(N=3,M=4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])