In [51]:
import numpy as np

### Indexing And Slicing

### 1-DIM

In [52]:
a1=np.array([10,20,30,40,50,60,70,80])
print(a1)

[10 20 30 40 50 60 70 80]


In [53]:
print(a1[0],end='\n\n\n')
print(a1[::-1],end='\n\n\n')
print(a1[::2],end='\n\n\n')

10


[80 70 60 50 40 30 20 10]


[10 30 50 70]




## 2-DIM

In [54]:
a2=np.array([[10,20,30,40],
             [50,60,70,80],
             [11,12,13,14],
             [15,16,17,18],
             [5,2,1,95]])
a2

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [11, 12, 13, 14],
       [15, 16, 17, 18],
       [ 5,  2,  1, 95]])

In [55]:
print(a2[0],end='\n\n\n')     # it can execute first row
print(a2[0,0],end='\n\n\n')    # it can execute first row first column
print(a2[::2],end='\n\n\n')     # it can execute every second row
print(a2[0,::2],end='\n\n\n')   # it can execute first row first 2 coloum
print(a2[::,0],end='\n\n\n')     # it can execute  all row first coloumn
print(a2[::-1,0],end='\n\n\n')    # it can execute reverse first coloumn
print(a2[2:,2],end='\n\n\n')      # it can execute row 2 onward third coloumn
print(a2[::-2],end='\n\n\n')    # it can execute reverse every 2nd row

[10 20 30 40]


10


[[10 20 30 40]
 [11 12 13 14]
 [ 5  2  1 95]]


[10 30]


[10 50 11 15  5]


[ 5 15 11 50 10]


[13 17  1]


[[ 5  2  1 95]
 [11 12 13 14]
 [10 20 30 40]]




In [56]:
print(a2[0,0],end='\n\n\n')

10




In [57]:
print(a2[::2],end='\n\n\n')

[[10 20 30 40]
 [11 12 13 14]
 [ 5  2  1 95]]




## 3-DIM

In [58]:
a3=np.array([[[10,20,30,40],[50,60,70,80],[90,100,110,120]],
             [[11,21,31,41],[51,61,71,81],[91,101,111,121]]])
print(a3)

[[[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]

 [[ 11  21  31  41]
  [ 51  61  71  81]
  [ 91 101 111 121]]]


In [59]:
print(a3[0],end='\n\n\n')          # it can execute first block
print(a3[:,0],end='\n\n\n')        # it can execute first row from all blocks
print(a3[::-1],end='\n\n\n')       # it can execute reverse blocks
print(a3[::-1,0,:],end='\n\n\n')   # it can execute reverse blocks first row
print(a3[0,0,0],end='\n\n\n')      # it can execute single element
print(a3[1,:,0],end='\n\n\n')      # it can execute second block first column
print(a3[1,:,::2],end='\n\n\n')    # it can execute second block alternate columns

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


[[10 20 30 40]
 [11 21 31 41]]


[[[ 11  21  31  41]
  [ 51  61  71  81]
  [ 91 101 111 121]]

 [[ 10  20  30  40]
  [ 50  60  70  80]
  [ 90 100 110 120]]]


[[11 21 31 41]
 [10 20 30 40]]


10


[11 51 91]


[[ 11  31]
 [ 51  71]
 [ 91 111]]




### Brodcasting

In [60]:
a1=np.array([10,20,30])
a2=np.array([1,2,3])
print(a1.shape,a2.shape,sep='\n')

(3,)
(3,)


In [61]:
a3=np.array([[10,20,30],[5,15,15]])
a4=np.array([[1,2,3],[8,9,3]])
print(a3.shape,a4.shape,sep='\n')

(2, 3)
(2, 3)


In [62]:
a5=np.array([[10,20,30],[40,50,60]])
a6=np.array([1,2,3])
print(a5.shape,a6.shape,sep='\n')

(2, 3)
(3,)


In [63]:
a7=np.array([[[10,20],[30,40]],[[40,50],[60,70]]])
a8=np.array([1,2])
print(a7.shape,a8.shape,sep='\n')

(2, 2, 2)
(2,)


In [64]:
a7=np.array([[10,20],[40,50]])
a8=np.array([1,2])
print(a7.shape,a8.shape,sep='\n')

(2, 2)
(2,)


In [65]:
x=np.array([[10,20],[40,50]])
y=np.array([[9,2],[7,8]])
print(x.shape,y.shape,sep='\n')
print(x+y)

(2, 2)
(2, 2)
[[19 22]
 [47 58]]
