In [7]:
import numpy as np

# ARRAY

1. ARRAY is an homogenenous collection 

2. array support duplicate ,indexing ,slicicing,(+ve,-ve)

3. array is an ordered collection

4. arary is partially mutable (only updating is possible) 

5. array is fixed size 

6. arary supports element wise operation

7. array support brodcasting

8. array is faster than list (because array store the data in contiguous memory)

   contiguous memory -->possible because of homogeneous

# type of array

0-Dimensional array  (Scalar array / 0darry)

1-Dimensional array   (vector / 1 darray)

2-Dimensional array   (matrix / 2darray)

n-Dimensional array    (multi dimensonal array / ndarray)

In [8]:
l1=[10,20,30,40,10,10]
l2=[10,100.5,20,30]
l3=[55,55.9,'python']
l4=[55,55.5,6+9j]

In [9]:
a1= np.array(l1)
a2= np.array(l2)
a3= np.array(l3)
a4= np.array(l4)

In [10]:
print(a1,type(a1),end='\n\n')
print(a2,type(a2),end='\n\n')
print(a3,type(a3),end='\n\n')
print(a4,type(a4),end='\n\n')

[10 20 30 40 10 10] <class 'numpy.ndarray'>

[ 10.  100.5  20.   30. ] <class 'numpy.ndarray'>

['55' '55.9' 'python'] <class 'numpy.ndarray'>

[55. +0.j 55.5+0.j  6. +9.j] <class 'numpy.ndarray'>



In [11]:
a1[::-1] # slicing

array([10, 10, 40, 30, 20, 10])

In [12]:
a1[0]  # indexing

np.int64(10)

In [13]:
a1[0]=999
print(a1)

[999  20  30  40  10  10]


In [14]:
# a1 dosent support new insertion or element removal

# Element by operation

In [15]:
x=np.array([2,4,6,8])
y=np.array([5,4,6,3])

In [16]:
print(x,y,sep='\n')

[2 4 6 8]
[5 4 6 3]


In [17]:
print(len(x),len(y),sep= '\n')

4
4


In [18]:
# arithematic poperator
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x//y)
print(x%y)

[ 7  8 12 11]
[-3  0  0  5]
[10 16 36 24]
[0.4        1.         1.         2.66666667]
[0 1 1 2]
[2 0 0 2]


In [19]:
# relational operator

print(x==y)
print(x!=y)
print(x>y)
print(x<y)
print(x>=y)
print(x<=y)


[False  True  True False]
[ True False False  True]
[False False False  True]
[ True False False False]
[False  True  True  True]
[ True  True  True False]


In [20]:
#bitwise operators

print(x&y)
print(x|y)
print(x^y)
print(x<<y)
print(x>>y)
print(~x)



[0 4 6 0]
[ 7  4  6 11]
[ 7  0  0 11]
[ 64  64 384  64]
[0 0 0 1]
[-3 -5 -7 -9]


In [21]:
#logical operators
# x==y 
(x==y).all() and (x>y).any()
# np.logical_and(x==y,x>y)

np.False_

In [22]:
np.logical_and(x==y,x>y)

array([False, False, False, False])

In [23]:
np.logical_or(x==y,x>y)

array([False,  True,  True,  True])

In [24]:
np.logical_not(x==y)

array([ True, False, False,  True])

In [25]:
np.logical_xor(x==y,x>y)

array([False,  True,  True,  True])

In [26]:
# membership operator
8 in x

True

In [27]:
print(8 in x)
# print(18 in x)   
print(18 not in x)

True
True


In [28]:
x in y

True

In [29]:
np.isin(x,y)

array([False,  True,  True, False])

In [30]:
# identity operator 

m=np.array([10,20])
n=np.array([10,20])

print(m,id(m),sep='-->')
print(n,id(n),sep='-->')

print(m is n)

[10 20]-->2425015828912
[10 20]-->2425015830640
False
