In [6]:
import numpy as np

In [7]:
# scaler array

a0= np.array(67) # 67 or 6.9 or 6+9j or 'programming' any permitive data type
print(a0)
print(a0.ndim)  # no_of diamensional (array diamensional)
print(a0.dtype) # data type of array elements
print(a0.itemsize) # memory utilized by single element(in n bytes)
print(a0.nbytes) #memory utilized by array (in bytes)
print(a0.shape) # no of element of each diamensional
print(a0.size) # total element

67
0
int64
8
8
()
1


In [8]:
# one  diamensional array

a1= np.array([10,20,30])
print(a1)
print(a1.ndim)
print(a1.size) # total element
print(a1.dtype) # data type of array elements
print(a1.itemsize) # memory utilized by single element(in n bytes)
print(a1.nbytes) #memory utilized by array (in bytes)
print(a1.shape) # no of element of each diamensional

[10 20 30]
1
3
int64
8
24
(3,)


In [9]:
# two  diamensional array

a2= np.array([[10,20,30],[50,40,20]])    # if see the any two bracaket that two diamensional
print(a2)
print(a2.ndim)
print(a2.size) # total element
print(a2.dtype) # data type of array elements
print(a2.itemsize) # memory utilized by single element(in n bytes)
print(a2.nbytes) #memory utilized by array (in bytes)
print(a2.shape) # no of element of each diamensional

[[10 20 30]
 [50 40 20]]
2
6
int64
8
48
(2, 3)


In [10]:
# three diamesional array

a3= np.array([[[10,20],[30,40],[11,12]],[[60,70],[12,14],[50,20]]])    
print(a3)
print(a3.size) # total element
print(a3.ndim)
print(a3.dtype) # data type of array elements
print(a3.itemsize) # memory utilized by single element(in n bytes)
print(a3.nbytes) #memory utilized by array (in bytes)
print(a3.shape) # no of element of each diamensional

[[[10 20]
  [30 40]
  [11 12]]

 [[60 70]
  [12 14]
  [50 20]]]
12
3
int64
8
96
(2, 3, 2)
