In [69]:
import numpy.random as rd

# method to create a array using random module
1. randint()
2. choise()
3. rand()
4. randn()
5. seed()

### randinit()
return the arary of random integer b/w low(inclusive) and high (exclusive) and both are mandotry

In [70]:
rd.randint(low=10,high=20)


17

In [71]:
rd.randint(low=10,high=20,size=(3,2))

array([[14, 16],
       [19, 12],
       [16, 17]], dtype=int32)

### choise()

In [72]:
rd.choice(['red','pink','pink','blue','violet','black'])

np.str_('violet')

In [73]:
rd.choice(['red','pink','pink','blue','violet','black'],size=(3,))
# rd.choice(['red','pink','pink','blue','violet','black'],size=(3,2))

array(['blue', 'pink', 'black'], dtype='<U6')

In [74]:
rd.choice(['red','pink','pink','blue','violet','black'],size=(3,),replace=False)

array(['red', 'pink', 'black'], dtype='<U6')

In [75]:
rd.choice(['red','pink','pink','blue','violet','black'],size=(6,),replace=False)
# rd.choice(['red','pink','pink','blue','violet','black'],size=(7,),replace=False)
# Cannot take a larger sample than population when 'replace=False'

array(['pink', 'black', 'violet', 'red', 'blue', 'pink'], dtype='<U6')

In [76]:
rd.choice(['red','pink','pink','blue','violet','black'],size=(3,),
          p=[0.2,0,0.5,0.1,0,0.2])  # sum of probabilities must be 1

array(['pink', 'red', 'red'], dtype='<U6')

### rand()

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).0(inclusive) and 1 (exclusive)

In [77]:
rd.rand()

0.5247746602583891

In [78]:
rd.rand(3)

array([0.39986097, 0.04666566, 0.97375552])

In [79]:
rd.rand(3,2)

array([[0.23277134, 0.09060643],
       [0.61838601, 0.38246199],
       [0.98323089, 0.46676289]])

### randn()
return a simple (or sample ) from the "standard normal"distribution.
mean nearly eqal to std nearly equal to 1

In [80]:
rd.randn() # if you dont pass the any value its fetch the 1 value

0.41701110966317523

In [81]:
rd.randn(3,)

array([ 0.83246186, -0.29339915, -0.02983857])

In [82]:
x=rd.randn(3,4)
x

array([[ 0.09512578,  0.66465434, -0.1402185 , -0.0331934 ],
       [-0.74907652, -0.77838201,  0.94884286,  1.58085059],
       [-0.36817094,  0.37556463, -1.19315823, -0.4090519 ]])

In [83]:
print(x.mean())
print(x.std())

-0.0005177746540535924
0.7585901565845938


### seed(seed_val)

fixed the randam values 

In [85]:
rd.seed(42)
print(rd.randint(5,10,3))
print(rd.choice([10,20,30,40,50],size=3))
print(rd.rand(3))
print(rd.randn(3))

[8 9 7]
[50 50 20]
[0.15599452 0.05808361 0.86617615]
[ 1.57921282  0.76743473 -0.46947439]
