In [111]:
import numpy as np

In [112]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
print(np.sum(a1))
print(np.mean(a1))
print(np.max(a1))
print(np.min(a1))
print(np.size(a1))
print(np.median(a1))  # internally sorts into ase order before calculating the 50th% data 

55
5.5
10
1
10
5.5


In [114]:
print(np.percentile(a1,25))  # 25% of data lice beloe 3.25
print(np.percentile(a1,50))  # 50 of data lice beloe 5.5
print(np.percentile(a1,75))  # 7% of data lice beloe 7.75
print(np.percentile(a1,60))  # 60%data lice beloe 6.39
# internally sort into ase order before calculating

3.25
5.5
7.75
6.3999999999999995


# copy() and 

In [115]:
x1=np.array([1,2,3])
x2=np.copy(x1)
print(x1,x2,sep='\n')
print("after modification of x1")
x1[0]=100
print(x1,x2,sep='\n')
print("x1 and x2 are independent variable")


[1 2 3]
[1 2 3]
after modification of x1
[100   2   3]
[1 2 3]
x1 and x2 are independent variable


In [116]:
y1=np.array([1,2,3])
y2=np.copy(y1)
print(x1,x2,sep='\n')
print("after modification of y1")
y1[0]=100
print(y1,y2,sep='\n')
print("y1 and y2 are dependent variable")


[100   2   3]
[1 2 3]
after modification of y1
[100   2   3]
[1 2 3]
y1 and y2 are dependent variable


# np.reshape()

In [117]:
z1=np.arange(1,13,1)
print(f'z1={z1} and length of array is  {z1.size}')
# choose the factores of 12(len) for reshaping
# (1,12) (12,1) (2,6) (6,2) (3,4) (4,3)
# (1,12,1) (12,1,1) (2,3,2) (2,2,3)
# (1,12,1,1) (12,1,1,1) (2,3,2,1) (2,2,3,1)

print(np.reshape(z1,shape=((2,6))),end='\n\n')
print(np.reshape(z1,shape=((2,3,2))),end='\n\n')

z1=[ 1  2  3  4  5  6  7  8  9 10 11 12] and length of array is  12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]



In [118]:
z2=np.array([[10,20,30],[40,50,60]])  # (2,3)
print(z2,end='\n\n')
res=np.reshape(z2,shape=-1) # ndarray to 1d array
print(res)
# print(f'\n {'-'*25} \n shallow copy or view ?\n {'-'*25} \n')
print("shallow copy or view ? ")
z2[0,0]=100
print(z2,res ,sep='\n\n')  # reshape and return view

[[10 20 30]
 [40 50 60]]

[10 20 30 40 50 60]
shallow copy or view ? 
[[100  20  30]
 [ 40  50  60]]

[100  20  30  40  50  60]


In [119]:
np.reshape(z2,shape=(3,2))   # dim remain same but shape is changed

array([[100,  20],
       [ 30,  40],
       [ 50,  60]])

# np.ravel

In [120]:
z3=np.array([[10,20,30],[40,50,60]])
res=np.ravel(z3)  # ndarray to 1darray (return view of z3)
z3[0,0]=500
print(z3,res,sep='\n\n')

[[500  20  30]
 [ 40  50  60]]

[500  20  30  40  50  60]


# arr_name.flatten()

In [121]:
z4=np.array([[10,20,30],[40,50,60]]) #(2,3)
z4.flatten()   # ndarray to 1darray (return shallow copy of z4 )
z4[0,0]=500
print(z4,res,sep='\n\n')

[[500  20  30]
 [ 40  50  60]]

[500  20  30  40  50  60]


# filteration

In [122]:
arr1=np.arange(11,16)
print(arr1)


[11 12 13 14 15]


In [123]:
arr1[[False,True,False,True,False]]  

array([12, 14])

In [128]:
arr1[(arr1%2==0)]

array([12, 14])

In [ ]:
np.where(arr1%2==0)  # index position where true is present

(array([1, 3]),)

In [127]:
arr1[np.where(arr1%2==0)] 


array([12, 14])

In [ ]:
np.where(arr1%2==0,'even','odd') 


array(['odd', 'even', 'odd', 'even', 'odd'], dtype='<U4')

# isin()

In [129]:
a1=np.array([10,20,30,40,50])
a2=np.array([20,50])
np.isin(a1,a2)

array([False,  True, False, False,  True])

In [132]:
for i in a1:
    print(i)

10
20
30
40
50


# agg with 2darray()

In [134]:
a1=np.array([[10,20],[30,40]])
print(np.sum(a1,axis=0))  # 0th element of each braket 1st element of each bracket
# [10+30,20+40]===>[40,60]
#------------------------------------------------------------------
print(np.sum(a1,axis=1))  # inner element are addad up ( withi the same bracket )
# [10+20 , 30+40]----->[30,70]

[40 60]
[30 70]
